# Generated by Django 3.2.8 on 2021-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_photo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='photo',
            field=models.FilePathField(blank=True),
        ),
    ]
