# Generated by Django 3.2.8 on 2021-10-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personal_data_table'),
        ('tasks', '0002_tasks_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ManyToManyField(to='users.Employee'),
        ),
    ]
