# Generated by Django 3.2.8 on 2021-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_comment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtask',
            field=models.IntegerField(default=None),
        ),
    ]
