# Generated by Django 3.2.8 on 2022-02-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tasksCount',
        ),
    ]
