# Generated by Django 3.2.8 on 2021-10-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('tasksCount', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(default=None)),
            ],
        ),
    ]
