# Generated by Django 3.2.8 on 2021-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_no_time_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=None),
        ),
    ]
