# Generated by Django 3.2.8 on 2021-10-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=30)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.employee')),
            ],
        ),
    ]
