# Generated by Django 3.2.8 on 2021-10-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personal_data_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
